image: python:3.12-slim

# Define rules for merge requests
.rules_for_merge_requests: &rules_for_merge_requests
  if: '$CI_MERGE_REQUEST_ID'
  when: always

cache:
  paths:
    - ~/.cache/pip
    - ~/.platformio/.cache

stages:
  - build

before_script:
  - ping -c 3 8.8.8.8
  - ping -c pypi.org
  - nslookup pypi.org
  - echo "nameserver 8.8.8.8" > /etc/resolv.conf
  - ping -c 3 8.8.8.8
  - ping -c pypi.org
  - nslookup pypi.org
  - pip install -U platformio --no-cache-dir -vvv

test_build:
  stage: build
  rules:
    - <<: *rules_for_merge_requests
  variables:
    PLATFORMIO_CI_SRC: examples/CompileTest
  script:
    - pio ci --project-conf ./platformio.ini --environment zeroUSB --lib . --lib lib/mpu6050-custom
